reorganize a bit. make kpack-from-image write all data to one dir.
make maas-cloudimg2eph call kpack-from-image and collect the expected
files out.  This makes kpack-from-image much more generic.

bzr-revno: 173.1.10

diff --git a/bin/kpack-from-image b/bin/kpack-from-image
--- a/bin/kpack-from-image
+++ b/bin/kpack-from-image
@@ -8,13 +8,14 @@ fail() { [ $# -eq 0 ] || error "$@"; exit 1; }
 
 Usage() {
     cat <<EOF
-Usage: ${0##*/} [ options ] image kernel-package kernel-out initrd-out [dtb-out] [dtb-name]
+Usage: ${0##*/} [ options ] image kernel-package out-dir
 
   Install kernel-package into image and copy the generated kernel
-  and initrd out into kernel-out and initrd-out.
-  'dtb-out' is the device tree blob (dtb-<version-flavor>)
-  'dtb-name' is filename for the device tree blob
-
+  and initrd out into out-dir
+    out-dir/
+      kernel
+      initrd
+      dtb-<filename>.dtb # for each file in lib/firmare/<ver>/device-tree
 
   Requires sudo to invoke mount-image-callback.
 
@@ -70,10 +71,9 @@ kernel_from_mp() {
         shift;
     done
 
-    [ $# -eq 2 -o $# -eq 4 -o $# -eq 6 ] ||
-        { bad_Usage "expected 4 or 6 args, got $# [$*]"; return; }
-    local mp="$1" kpkg="$2" kout="$3" iout="$4" 
-    local dtb_out="$5" dtb_name="$6"
+    [ $# -eq 3 ] ||
+        { bad_Usage "expected 3 args, got $# [$*]"; return; }
+    local mp="$1" kpkg="$2" outd="$3"
 
     local me="" myd=""
     me=$(readlink -f "$0") && myd="${me%/*}" ||
@@ -86,38 +86,33 @@ kernel_from_mp() {
             kihelper="$myd/$kihelper"
         fi
     fi
+    [ -d "$outd" ] || mkdir -p "$outd" ||
+        { error "failed mkdir $outd"; return 1; }
 
+    local ch_outd="/tmp/output"
     KPACK_SKIP_APT_UPDATE=$skip_update \
-        chroot "$mp" /bin/bash -s chrooted "$kpkg" < "$me" ||
+        chroot "$mp" /bin/bash -s chrooted "$kpkg" "$ch_outd" < "$me" ||
         { error "failed chroot and kernel install"; return 1; }
-
-    kernel="vmlinuz"
-    initrd="initrd.img"
-    if [ -n "$chown_to" ]; then
-        ( cd "$mp/tmp" && chown "$chown_to" $kernel $initrd ) || {
-            error "failed chown $mp/tmp/{kernel,initrd}";
-            return 1;
-        }
-    fi
 
     if [ -n "$kihelper" ]; then
         local verflav=""
         read verflav < "$mp/tmp/verflav"
         debug 1 "using $kihelper verflav='$verflav'"
         ROOT="$mp" VERSION_FLAVOR="$verflav" "$kihelper" \
-            "$mp/tmp/$kernel" "$mp/tmp/$initrd" ||
+            "$mp/${ch_outd}/kernel" "$mp/${ch_outd}/initrd" ||
         { error "$kihelper failed"; return 1; }
     fi
-    mv "$mp/tmp/$kernel" "$kout" &&
-        mv "$mp/tmp/$initrd" "$iout" ||
-        { error "failed to copy kernel/initrd from $mp"; return 1; }
-    if [ -n "${dtb_name}" ]; then
-	dtb_file=$(find $mp/lib/firmware/$verflav/device-tree/ -iname $dtb_name)
-	if [ ! -z "$dtb_file" ]; then
-	    cp $dtb_file $dtb_out ||
-	    { error "failed to copy out dtb file"; return 1; }
-        fi
+
+    if [ -n "$chown_to" ]; then
+        ( cd "$mp/$ch_outd" && chown "$chown_to" * ) || {
+            error "failed chown $mp/$ch_outd/*";
+            return 1;
+        }
     fi
+
+    mv "$mp/$ch_outd/"* "$outd" ||
+        { error "failed move files from chrooted outdi '$ch_outd'"; return 1; }
+
 }
 
 config_addl_modules() {
@@ -144,10 +139,11 @@ chrooted() {
     local skip_update=${KPACK_SKIP_APT_UPDATE:-false}
     local verflav initrd kernel
     export LANG=C
-    pkgs=( "$@" )
     kpkg="$1"
+    outd="$2"
 
-    local stamp="/tmp/stamp"
+    mkdir -p "$outd" || { error "failed mkdir $outd"; return 1; }
+    local stamp="$outd/stamp"
     touch "$stamp"
 
     $skip_update || apt-get update -q ||
@@ -196,7 +192,7 @@ chrooted() {
 
     [ -f "$initrd" ] || { error "no initrd for $verflav" 1>&2; return 1; }
 
-    local name="" t="" outd="/tmp" outf=""
+    local name="" t="" outf=""
     for f in /boot/*-${verflav}; do
         case "$f" in
             vmlinu?*) name="kernel";;
@@ -209,6 +205,14 @@ chrooted() {
         outf="$outd/$name"
         cp "$f" "$outf" && chmod ugo+r "$outf" ||
             { error "failed to copy '$name' from '$f'"; return 1; }
+    done
+
+    local path="/lib/firmware/$verflav/device-tree"
+    for f in "/lib/firmware/$verflav/device-tree"/*; do
+        [ -f "$f" ] || continue
+        outf="$outd/device-tree-${f##*/}"
+        cp "$f" "$outf" && chmod ugo+r "$outf" ||
+            { error "failed to copy '$outf' from '$f'"; return 1; }
     done
 
     echo "$verflav" > "$outd/verflav" ||
@@ -241,10 +245,9 @@ main() {
         shift;
     done
 
-    [ $# -eq 2 -o $# -eq 4 -o $# -eq 6 ] ||
-        { bad_Usage "expected 4 or 6 args, got $#"; return; }
-    local img="$1" kpkg="$2" kern_out=${3:-kernel} initrd_out=${4:-initrd}
-    local dtb_out="$5" dtb_name="$6"
+    [ $# -eq 3 ] ||
+        { bad_Usage "expected 3 args, got $#"; return; }
+    local img="$1" kpkg="$2" outd=${3}
 
     TEMP_D=$(mktemp -d "${TMPDIR:-/tmp}/${0##*/}.XXXXXX") ||
         fail "failed to make tempdir"
@@ -280,11 +283,11 @@ main() {
             --system-resolvconf "$myimg" -- "$0" "kernel_from_mp" \
             _MOUNTPOINT_ "--chown-to=$chown_to" \
             ${kihelper:+"--kihelper=$kihelper"} \
-            "$kpkg" "$kern_out" "$initrd_out" ${dtb_out:+"${dtb_out}"} \
-	    ${dtb_name:+"${dtb_name}"} || 
+            "$kpkg" "$outd" ||
     { error "failed"; return 1; }
 
-    error "wrote to $kern_out, $initrd_out, ${dtb_out:+${dtb_out}}, ${dtb_name:+${dtb_name}}"
+    error "wrote to $outd"
+    error "  " $(cd "$outd" && echo *)
     return
 }
 
diff --git a/bin/maas-cloudimg2eph2 b/bin/maas-cloudimg2eph2
--- a/bin/maas-cloudimg2eph2
+++ b/bin/maas-cloudimg2eph2
@@ -235,6 +235,64 @@ allow_resize_failure() {
     fi
 }
 
+handle_kpack() {
+    local short_opts="v"
+    local long_opts="dtb:,kihelper:"
+    local getopt_out=""
+    getopt_out=$(getopt --name "handle_kpack" \
+        --options "${short_opts}" --long "${long_opts}" -- "$@") &&
+        eval set -- "${getopt_out}" ||
+        { bad_Usage; return; }
+
+    local dtbs pt img outd ckpkg tkout tiout
+    dtbs=( )
+    pt=( )
+    while [ $# -ne 0 ]; do
+        cur="$1"; next="$2";
+        case "$cur" in
+               --dtb) dtbs[${#dtbs[@]}]="$next"; shift;;
+               --kihelper) pt[${#pt[@]}]="$cur=$next"; shift;;
+            --) shift; break;;
+        esac
+        shift;
+    done
+    # tkout, tiout = target kernel out, target initrd out
+    img="$1"; ckpkg="$2"; tkout="$3"; tiout="$4"
+    shift 4
+    outd="${TEMP_D}/$ckpkg"
+    mkdir -p "$outd" ||
+        { error "failed tempdir for '$ckpkg'"; return 1; }
+
+    ddebug 1 "$(date -R): starting kpack-from-image for $ckpkg/${pt[*]}"
+    KPACK_SKIP_APT_UPDATE=true kpack-from-image ${vflags} "${pt[@]}" \
+        "$imgfile" "$ckpkg" "$outd" ||
+        { error "failed to get $ckpkg output"; return 1; }
+    ensure_file_d "$tkout" "$tiout" ||
+        { error "failed to make dirs for $tkout or $tiout"; return 1; }
+    mv "$outd/kernel" "$tkout" &&
+        mv "$outd/initrd" "$tiout" ||
+        { error "failed copying files"; return 1; }
+
+    local darg="" bname="" outf=""
+    for darg in "${dtbs[@]}"; do
+        # format is name=output. and kpack-from-image names
+        # files dtb-<name>
+        bname=${darg%%=*}
+        outf=${darg#*=}
+        ensure_file_d "$outf" || { error "failed mkdir for $outf"; return 1; }
+        if [ -f "$outd/dtb-$bname" ]; then
+            mv "$outd/dtb-$bname" "$outf" ||
+                { error "failed moving dtb-$bname to $outf"; return 1; }
+        elif [ -f "$outd/dtb-$bname.dtb" ]; then
+            mv "$outd/dtb-$bname.dtb" "$outf" ||
+                { error "failed moving dtb-$bname.dtb to $outf"; return 1; }
+        else
+            error "did not find dtb file $bname"
+            return 1;
+        fi
+    done
+}
+
 main() {
     local short_opts="a:hk:p:v"
     local long_opts="arch:,help,kernel:,krd-pack:,no-gzip,verbose"
@@ -333,42 +391,11 @@ main() {
         "$kpkg" "$pkout" "$piout" "$manif" ||
         { error "failed to turn $imgfile to ephemeral"; return 1; }
 
-    local i="" ckpkg="" ckout="" ciout="" subarch="" oifs="$IFS"
+    local i="" oifs="$IFS"
     ddebug 1 "starting kpacks: ${kpacks[*]}"
     for i in "${kpacks[@]}"; do
         IFS=","; set -- $i; IFS="$oifs"
-        # tkout, tiout = target kernel out, target initrd out
-        ckpkg="$1"; tkout="$2"; tiout="$3"
-        shift 3
-        flags=( "$@" )
-        ckout="${TEMP_D}/$ckpkg-kernel"
-        ciout="${TEMP_D}/$ckpkg-initrd"
-	if [ -n "$4" ] 
-	then
-	    tdout="$4"
-	    cdout="${TEMP_D}/$ckpkg-dtb"
-            ddebug 1 "$(date -R): starting kpack-from-image for $ckpkg/${flags[*]}"
-            KPACK_SKIP_APT_UPDATE=true kpack-from-image ${vflags} "$imgfile" \
-                "$ckpkg" "$ckout" "$ciout" "$cdout" "${flags[@]}" ||
-                { error "failed to get $ckpkg output"; return 1; }
-            ensure_file_d "$tkout" "$tiout" ||
-                { error "failed to make dirs for $tkout or $tiout"; return 1; }
-            mv "$ckout" "$tkout" &&
-                mv "$ciout" "$tiout" && 
-		mv "$cdout" "$tdout" ||
-                { error "failed copying files"; return 1; }
-	else
-            ddebug 1 "$(date -R): starting kpack-from-image for $ckpkg/${flags[*]}"
-            KPACK_SKIP_APT_UPDATE=true kpack-from-image ${vflags} "$imgfile" \
-                "$ckpkg" "$ckout" "$ciout" "${flags[@]}" ||
-                { error "failed to get $ckpkg output"; return 1; }
-            ensure_file_d "$tkout" "$tiout" ||
-                { error "failed to make dirs for $tkout or $tiout"; return 1; }
-            mv "$ckout" "$tkout" &&
-                mv "$ciout" "$tiout" ||
-                { error "failed copying files"; return 1; }
-	fi
-	
+        handle_kpack "$imgfile" "$@"
     done
     ddebug 1 "kpacks done"
 
