Install linux-firmware package on CentOS 7
Upstream doesn't include linux-firmware on CentOS 7 which is required for certain hardware. Extra CentOS packages are now defined in the yaml file.

bzr-revno: 329.4.1

diff --git a/bin/maas-qcow2targz b/bin/maas-qcow2targz
--- a/bin/maas-qcow2targz
+++ b/bin/maas-qcow2targz
@@ -21,57 +21,10 @@
 # You should have received a copy of the GNU Affero General Public License
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
-PYTHON_OAUTH_RPM_URL="https://kojipkgs.fedoraproject.org/packages/"\
-"python-oauth/1.0.1/10.el7/noarch/python-oauth-1.0.1-10.el7.noarch.rpm"
 TEMP_D=""
 
 error() { echo "$@" 1>&2; }
 fail() { [ $# -eq 0 ] || error "$@"; exit 1; }
-
-maasify() {
-    local root_d="$1" out="$2" curtin_path="$3"
-
-    if [ -n "$curtin_path" ]; then
-        mkdir -p "$root_d/curtin" ||
-            { error "failed to create /curtin"; return 1; }
-        cp -r "$curtin_path/"* "$root_d/curtin/" || {
-            error "failed copying $CURTIN_PATH to $root_d/curtin";
-            return 1;
-        }
-        chmod +x "$root_d/curtin/"* ||
-            { error "failed chmod +x $root_d/curtin/*"; return 1; }
-    fi
-
-    # CentOS 7 removed python-oauth which is required for cloud-init to
-    # authenticate with the MAAS metadata service. Until cloud-init from CentOS
-    # supports python-oauth2 we need to pull python-oauth from EPEL7-testing
-    local fname="" url="$PYTHON_OAUTH_RPM_URL"
-    if [ -f "$root_d/etc/os-release" ] &&
-        grep -qc "centos:7" "$root_d/etc/os-release"; then
-        error "CentOS 7 detected! Adding python-oauth for MAAS cloud-init..."
-        fname="/tmp/${PYTHON_OAUTH_RPM_URL##*/}"
-        dl "$url" "$root_d/$fname" &&
-            LANG=C chroot "$root_d" rpm -ivh "$fname" &&
-            rm "$root_d/$fname" || {
-                error "failed dl and installation of $url"
-                return 1
-            }
-    fi
-
-    error "Taring up image contents... into $out"
-    local gzflag="--use-compress-program=gzip"
-    if command -v pigz >/dev/null 2>&1; then
-        gzflag="--use-compress-program=pigz"
-    fi
-    tar --directory "$root_d" --create --preserve-permissions \
-        --one-file-system \
-        --sparse --file "$out" $gzflag \
-        --xattrs "--xattrs-include=*" . || {
-        error "failed tar command"
-        rm -f "$out"
-        return 1
-    }
-}
 
 dl() {
     local url="$1" out="${2:-${1##*/}}"
@@ -91,10 +44,96 @@ dl() {
 
 cleanup() { [ -d "${TEMP_D}" ] && rm -Rf "${TEMP_D}"; }
 
-if [ "$1" = "maasify" ]; then
+function usage() {
+    echo "Usage $0 [options] <URL> <SHA256> <out file>"
+    echo "Options:"
+    echo "  --curtin-path   Path to any curtin files to include in the image."
+    echo "  --packages       Any extra packages to install into the image."
+
+}
+
+short_opts="c:p:h"
+long_opts="curtin-path:,packages:,help"
+
+getopt_out=$(getopt --name "${##*/}" --options "${short_opts}" --long "${long_opts}" -- "$@")
+if [ $? -ne 0 ]; then
+    usage
+    exit 1
+fi
+
+eval set -- "$getopt_out"
+while true; do
+    case "$1" in
+        -c|--curtin-path)
+            curtin_path=$2
+            shift 2
+            ;;
+        -p|--packages)
+            packages=$2
+            shift 2
+            ;;
+        -h|--help)
+            usage
+            exit 0
+            ;;
+        --)
+            shift
+            break
+            ;;
+    esac
+done
+
+if [ "$1" == "maasify" ]; then
     [ "$(id -u)" = "0" ] || { error "not root, sorry"; exit 1; }
-    "$@"
-elif [ $# -eq 3 ] || [ $# -eq 4 ]; then
+    root_d=$2
+    out=$3
+    if [ -n "$curtin_path" ]; then
+        mkdir -p "$root_d/curtin" ||
+            { error "failed to create /curtin"; return 1; }
+        cp -r "$curtin_path/"* "$root_d/curtin/" || {
+            error "failed copying $CURTIN_PATH to $root_d/curtin";
+            return 1;
+        }
+        chmod +x "$root_d/curtin/"* ||
+            { error "failed chmod +x $root_d/curtin/*"; return 1; }
+    fi
+
+    if [ -n "$packages" ]; then
+        # Make sure the mounted image has DNS
+        cp /etc/resolv.conf "${root_d}/etc/resolv.conf"
+        for package in $(echo $packages | sed 's/,/ /g'); do
+            LANG=C chroot "$root_d" yum -y install $package || {
+                error "failed to install $package"
+                exit 1
+            }
+        done
+        # Don't ship with yum cache
+        LANG=C chroot "$root_d" yum clean all || {
+                error "failed to clear yum cache"
+                exit 1
+            }
+        rm -f "${root_d}/etc/resolv.conf"
+    fi
+
+    error "Taring up image contents... into $out"
+    gzflag="--use-compress-program=gzip"
+    if command -v pigz >/dev/null 2>&1; then
+        gzflag="--use-compress-program=pigz"
+    fi
+    tar --directory "$root_d" --create --preserve-permissions \
+        --one-file-system \
+        --sparse --file "$out" $gzflag \
+        --xattrs "--xattrs-include=*" . || {
+        error "failed tar command"
+        rm -f "$out"
+        exit 1
+    }
+else
+    if [ $# -ne 3 ]; then
+        usage
+        exit 1
+    fi
+
     url=$1
     sha256=$2
     if [ "$(dirname $3)" == "." ]; then
@@ -102,7 +141,7 @@ elif [ $# -eq 3 ] || [ $# -eq 4 ]; then
     else
         out=$3
     fi
-    curtin_path=$4
+
     error "final output will be in ${out}"
 
     mkdir -p $(dirname "$out")
@@ -154,17 +193,17 @@ elif [ $# -eq 3 ] || [ $# -eq 4 ]; then
     cp "$img_path" "$working_img" ||
         fail "failed copying image ${img_path} -> ${working_img}"
 
+    cb_args="maasify _MOUNTPOINT_ $out"
+    [ -n "$curtin_path" ] && cb_args="$cb_args --curtin-path $curtin_path"
+    [ -n "$packages" ] && cb_args="$cb_args --packages $packages"
     sudo \
         CACHE_D="${cache_d}" \
         ${http_proxy:+"http_proxy=${http_proxy}"} \
         ${https_proxy:+"https_proxy=${https_proxy}"} \
         mount-image-callback --proc "$working_img" -- \
-        "$0" maasify _MOUNTPOINT_ "$out" ${curtin_path:+"${curtin_path}"}
+        "$0" $cb_args
 
     error "wrote $out"
-else
-    error "Usage: $0 <URL> <SHA256> <out file> [curtin file path]"
-    exit 1
 fi
 
 # vi: ts=4 expandtab
