maas-qcow2targz: more style cleanups. remove bash -e
instead of 'set -e', prefer to give error message and exit.

bzr-revno: 225.1.8

diff --git a/bin/maas-qcow2targz b/bin/maas-qcow2targz
--- a/bin/maas-qcow2targz
+++ b/bin/maas-qcow2targz
@@ -1,4 +1,4 @@
-#!/bin/bash -e
+#!/bin/bash
 #
 # maas-qcowtargz - Take a qcow2 or qcow2.xz file from a given URL or
 #                  file path and make it sufficient for use as a 
@@ -28,32 +28,43 @@ error() { echo "$@" 1>&2; }
 fail() { [ $# -eq 0 ] || error "$@"; exit 1; }
 
 maasify() {
-    local mnt_point="$1" out="$2" curtin_path="$3"
+    local root_d="$1" out="$2" curtin_path="$3"
 
-    if [ -d "$CURTIN_PATH" ]; then
-        mkdir -p "$mnt_point/curtin"
-        cp "$CURTIN_PATH/"* "$mnt_point/curtin/"
-        chmod +x "$mnt_point/curtin/"*
+    if [ -n "$curtin_path" ]; then
+        mkdir -p "$root_d/curtin" ||
+            { error "failed to create /curtin"; return 1; }
+        cp -r "$curtin_path/"* "$root_d/curtin/" || {
+            error "failed copying $CURTIN_PATH to $root_d/curtin";
+            return 1;
+        }
+        chmod +x "$root_d/curtin/"* ||
+            { error "failed chmod +x $root_d/curtin/*"; return 1; }
     fi
 
     # CentOS 7 removed python-oauth which is required for cloud-init to
     # authenticate with the MAAS metadata service. Until cloud-init from CentOS
     # supports python-oauth2 we need to pull python-oauth from EPEL7-testing
     local fname="" url="$PYTHON_OAUTH_RPM_URL"
-    if [ -f "$mnt_point/etc/os-release" ] &&
-        grep -qc "centos:7" "$mnt_point/etc/os-release"; then
-        echo "CentOS 7 detected! Adding python-oauth for MAAS cloud-init..."
+    if [ -f "$root_d/etc/os-release" ] &&
+        grep -qc "centos:7" "$root_d/etc/os-release"; then
+        error "CentOS 7 detected! Adding python-oauth for MAAS cloud-init..."
         fname="/tmp/${PYTHON_OAUTH_RPM_URL##*/}"
-        wget "$url" -O "$mnt_point/$fname" &&
-            LANG=C chroot "$mnt_point" rpm -ivh "$fname" &&
-            rm "$mnt_point/$fname" || {
+        wget "$url" -O "$root_d/$fname" &&
+            LANG=C chroot "$root_d" rpm -ivh "$fname" &&
+            rm "$root_d/$fname" || {
                 error "failed dl and installation of $url"
                 return 1
             }
     fi
 
-    echo "Taring up image contents..."
-    tar -C "$mnt_point" --one-file-system -czf "$out" .
+    error "Taring up image contents..."
+    tar --directory "$root_d" --create --preserve-permissions \
+        --sparse --file "$output" $gzflag \
+        --xattrs "--xattrs-include=*" . || {
+        error "failed tar command"
+        rm -f "$output"
+        return 1
+    }
 }
 
 if [ "$1" = "maasify" ]; then
@@ -81,34 +92,40 @@ elif [ $# -eq 3 ] || [ $# -eq 4 ]; then
         img_path="$url"
     fi
 
-    echo "Checking given sha256sum..."
-    sha256_out=$(sha256sum "$img_path")
-    found_sha256=${sha256_out%  *}
-    if [ "$found_sha256" != "$sha256" ]; then
-        echo "Error: sha256 of $img_path != $sha256"
-        exit 1
+    error "Checking sha256sum for $img_path"
+    sha256_out=$(sha256sum "$img_path") ||
+        fail "failed: sh256sum $img_path"
+    found=${sha256_out%  *}
+    if [ "$found" != "$sha256" ]; then
+        fail "Error: unexpected sha256 of $img_path $found != $sha256"
     fi
 
-    fout=$(LANG=C file "$img_path")
+    fout=$(LANG=C file "$img_path") ||
+        fail "failed file $img_path"
     case "${fout#$img_path: }" in
         "XZ compressed data"*)
             echo "Decompressing XZ image..."
-            new_img_path="${img_path%%'.xz'}"
-            [ -f "$new_img_path" ] && rm "$new_img_path"
-            unxz $img_path
+            new_img_path="${img_path%.xz}"
+            [ ! -f "$new_img_path" ] || rm -f "$new_img_path" ||
+                fail "$new_img_path existed, failed rm"
+            unxz "$img_path" ||
+                fail "failed unxz $img_path"
             img_path="${new_img_path}"
             ;;
     esac
 
     sudo \
         mount-image-callback --proc "$img_path" -- \
-        "$0" maasify _MOUNTPOINT_ "$out" "$curtin_path"
+        "$0" maasify _MOUNTPOINT_ "$out" ${curtin_path:+${"$curtin_path"}}
 
-    rm "$img_path"
+    if [ "$img_path" = "$url" ]; then
+        rm "$img_path" ||
+            fail "failed rm $img_path"
+    fi
 
     echo "Done!"
 else
-    echo "Usage: $0 <URL> <SHA256> <out file> [curtin file path]"
+    error "Usage: $0 <URL> <SHA256> <out file> [curtin file path]"
     exit 1
 fi
 
