maas-cloudimg2eph2: resize image to give working space and set size to 1400M
vivid images are too small coming out of build (http://pad.lv/1414062).
They're only ~1G which doesn't allow any space for installing linux-generic.

So to address that, we're
a.) adding some space before updating the image
b.) setting the final image size to 1400M explicitly.

also, moving 'zero' operation here rather than in cloudimg2ephemeral.

bzr-revno: 178

diff --git a/bin/maas-cloudimg2eph2 b/bin/maas-cloudimg2eph2
--- a/bin/maas-cloudimg2eph2
+++ b/bin/maas-cloudimg2eph2
@@ -105,6 +105,80 @@ ensure_file_d() {
     return 0
 }
 
+human2bytes() {
+    # converts size suitable for input to resize2fs to bytes
+    # s:512 byte sectors, K:kilobytes, M:megabytes, G:gigabytes
+    # none: block size of the image
+    local input=${1} defunit=${2:-1024}
+    local unit count;
+    case "$input" in
+        *s) count=${input%s}; unit=512;;
+        *K) count=${input%K}; unit=1024;;
+        *M) count=${input%M}; unit=$((1024*1024));;
+        *G) count=${input%G}; unit=$((1024*1024*1024));;
+        *)  count=${input}  ; unit=${defunit};;
+    esac
+   _RET=$((${count}*${unit}))
+}
+
+resize_image() {
+    # grow image 'img' by 'size' and return a string
+    # suitable for restoring via restore_image
+    local img="$1" size="$2" ret="" tok=":"
+    local oimgsize="" oblocks="" out="" blksize=""
+    local tbytes=""
+    out=$(ls -l "$img") && oimgsize=$(echo "$out" | awk '{print $5}') &&
+        [ -n "$oimgsize" ] ||
+        { error "failed to get size of $img"; return 1; }
+
+    case "$size" in
+        +*) human2bytes "${size#+}" ||
+                { error "failed convert '${size#+}' to bytes"; return 1; }
+            tbytes=$(($oimgsize+$_RET))
+            ;;
+        *) human2bytes "$size" ||
+                { error "failed convert '$size' to bytes"; return 1; }
+            tbytes=${_RET}
+            ;;
+    esac
+
+    out=$(LC_ALL=C dumpe2fs "$img" 2>/dev/null) ||
+        { error "failed 'dumpe2fs $img'"; return 1; }
+    oblocks=$(printf "%s\n" "$out" |
+        awk '$0 ~ /^Block count:/ { print $3 }') &&
+        [ -n "$oblocks" ] || {
+            error "failed to record blocks in $img"
+            return
+        }
+
+    blksize=$(printf "%s\n" "$out" |
+        awk '$0 ~ /^Block size:/ { print $3 }')
+
+    local tblocks=$(($tbytes/$blksize))
+    ddebug 1 "targetting $tbytes bytes. fs is currently $oblocks * $blksize."
+    ddebug 1 "resize to $tblocks blocks"
+
+    if [ "$oimgsize" -lt "$tbytes" ]; then
+        truncate --size=$tbytes "$img" ||
+            { error "failed to resize image to $tbytes"; return 1; }
+    fi
+
+    out=$(e2fsck -fy "$img" 2>&1) ||
+        { error "failed to e2fsck -fy '$img'"; error "$out"; return 1; }
+
+    out=$(resize2fs "$img" "$tblocks" 2>&1) ||
+        { error "failed resize '$img'"; error "$out"; return 1; }
+
+    if [ "$oimgsize" -gt "$tbytes" ]; then
+        truncate --size=$tbytes "$img"
+    fi
+
+    out=$(e2fsck -fy "$img" 2>&1) ||
+        { error "failed to e2fsck -fy '$img'"; error "$out"; return 1; }
+
+    _RET="$oimgsize:$oblocks"
+}
+
 main() {
     local short_opts="a:hk:p:v"
     local long_opts="arch:,help,kernel:,krd-pack:,no-gzip,verbose"
@@ -116,6 +190,7 @@ main() {
 
     local cur="" next="" output="" gzip=true kpkg=""
     local kpacks="" src_in="" src="" arch="" vflags=""
+    local working_space="1024M" zero_img="true" fs_img_size="1400M"
     kpacks=( )
 
     while [ $# -ne 0 ]; do
@@ -140,6 +215,11 @@ main() {
     PATH="$(dirname "$0"):$PATH"
     command -v "maas-cloudimg2ephemeral" >/dev/null 2>&1 ||
         { error "do not have maas-cloudimg2ephemeral in path"; return 1; }
+
+    [ -z "$kpkg" ] && {
+        error "no '--kernel' provided, choosing 'linux-generic'"
+        kpkg="linux-generic"
+    }
 
     TEMP_D=$(mktemp -d "${TMPDIR:-/tmp}/${0##*/}.XXXXXX") ||
         { error "failed to make tempdir"; return 1; }
@@ -180,11 +260,19 @@ main() {
     ensure_file_d "$output" ||
         { error "failed to create dir for $output"; return 1; }
 
+    local restore_img_info=""
+    if [ -n "$working_space" ]; then
+        ddebug 1 "getting '$working_space' in $imgfile"
+        resize_image "$imgfile" "+$working_space" ||
+            { error "failed to grow $imgfile by $working_space"; return 1; }
+        restore_img_info="$_RET"
+    fi
+
     # now imgfile has the root filesystem image to adjust
     local pkout="${TEMP_D}/$kpkg-kernel" piout="${TEMP_D}/$kpkg-initrd"
     local manif="${TEMP_D}/manifest"
     ddebug 1 "starting maas-cloudimg2ephemeral"
-    maas-cloudimg2ephemeral $vflags --zero \
+    maas-cloudimg2ephemeral $vflags \
         ${arch:+"--arch=$arch"} "$imgfile" \
         "$kpkg" "$pkout" "$piout" "$manif" ||
         { error "failed to turn $imgfile to ephemeral"; return 1; }
@@ -210,6 +298,20 @@ main() {
             { error "failed copying files"; return 1; }
     done
     ddebug 1 "kpacks done"
+
+    if [ -n "$fs_img_size" ]; then
+        ddebug 1 "setting final image to $fs_img_size"
+        resize_image "$imgfile" "$fs_img_size" || {
+            error "failed to set '$imgfile' to '$fs_img_size'"
+            return 1;
+        }
+    fi
+
+    if $zero_img; then
+        ddebug 1 "zeroing img"
+        e2fsck -fy "$imgfile" || { error "failed to e2fsck $imgfile"; return 1; }
+        zerofree "$imgfile" || { error "failed zerofree $imgfile"; return 1; }
+    fi
 
     if $gzip; then
         ddebug 1 "gzipping image file"
