allow resize image to fail for arm64 builds.
This allows resize to fail on cross (qemu-user) builds of arm64.
Its necessary as a hack to get us vivid builds.

bzr-revno: 185

diff --git a/bin/maas-cloudimg2eph2 b/bin/maas-cloudimg2eph2
--- a/bin/maas-cloudimg2eph2
+++ b/bin/maas-cloudimg2eph2
@@ -154,6 +154,9 @@ resize_image() {
         }
     fi
 
+    out=$(e2fsck -fy "$img" 2>&1) ||
+        { error "failed to e2fsck -fy '$img'"; error "$out"; return 1; }
+
     out=$(LC_ALL=C dumpe2fs "$img" 2>/dev/null) ||
         { error "failed 'dumpe2fs $img'"; return 1; }
     oblocks=$(printf "%s\n" "$out" |
@@ -206,6 +209,30 @@ resize_image() {
         { error "failed to e2fsck -fy '$img'"; error "$out"; return 1; }
 
     _RET="$oimgsize:$oblocks"
+}
+
+allow_resize_failure() {
+    local arch="$1" bdist="" barch=""
+    barch=${2:-$(uname -m)}
+    bdist=${3:-$(lsb_release -sc)}
+
+    if [ "$arch" = "arm64" ] &&
+       [ "$barch" = "x86_64" -o -z "${barch#i?86}" ] &&
+       [ "$bdist" = "utopic" -o "$bdist" = "vivid" ]; then
+        error "***************************"
+        error "WARN: resize2fs fail allowed for arch=$arch on dist=$bdist/$barch"
+        error "WARN: arm64 builds require utopic due to"
+        error "      'qemu: uncaught target signal 11'"
+        error "as seen http://tinyurl.com/koqo99m"
+        error "        http://paste.ubuntu.com/9900803/"
+        error ""
+        error "resize2fs is broken on utopic: http://pad.lv/1415077"
+        error "***************************"
+        return 0
+    else
+        error "resize image failure not allowed for $arch/$barch/$bdist"
+        return 1
+    fi
 }
 
 main() {
@@ -330,10 +357,12 @@ main() {
 
     if [ -n "$fs_img_size" ]; then
         ddebug 1 "setting final image to $fs_img_size"
-        resize_image "$imgfile" "$fs_img_size" || {
-            error "failed to set '$imgfile' to '$fs_img_size'"
-            return 1;
-        }
+        if ! resize_image "$imgfile" "$fs_img_size"; then
+            if ! allow_resize_failure "$arch"; then
+                error "failed resize of $imgfile"
+                return 1;
+            fi
+        fi
     fi
 
     if $zero_img; then
