move creation of ext[234] filesystems to a method and use it.
bzr-revno: 304.1.2

diff --git a/bin/maas-cloudimg2eph2 b/bin/maas-cloudimg2eph2
--- a/bin/maas-cloudimg2eph2
+++ b/bin/maas-cloudimg2eph2
@@ -3,6 +3,7 @@
 VERBOSITY=1
 TEMP_D=""
 VALID_FORMATS=( auto img-tar root-image root-image-gz root-tar squashfs-image )
+CLOUDIMG_LABEL="cloudimg-rootfs"
 
 error() { echo "$@" 1>&2; }
 fail() { [ $# -eq 0 ] || error "$@"; exit 1; }
@@ -59,6 +60,32 @@ debug() {
     error "${@}"
 }
 
+mkfs_ext4() {
+    local out="" cmd="" feature_flags="" cfg="/etc/mke2fs.conf" fstype="ext4"
+    case "$1" in
+        --type=*) fstype=${1#--type=}; shift;;
+        --type) fstype="$2"; shift 2;;
+    esac
+
+    local target="$1" label="$2" uuid="$3"
+    if grep -q metadata_csum "$cfg"; then
+        # disable metadata_csum as yakkety will create this by default
+        # but kernels on some buildd cannot mount such a filesystem.
+        feature_flags="^metadata_csum"
+    fi
+    cmd=( "mkfs.$fstype"
+        ${label:+-L "$label"} ${uuid:+-U "$uuid"}
+        ${feature_flags:+-O "$feature_flags"}
+        -F "$target" )
+    debug 1 "creating $fstype fs in '$target'. label=$label" \
+            " feature_flags='${feature_flags}'"
+    debug 2 "mkfs cmd: ${cmd[*]}"
+
+    out=$("${cmd[@]}" 2>&1) ||
+        { error "failed ${cmd[*]}"; error "$out"; return 1; }
+    return
+}
+
 get_img_from_tar() {
     local img="$1" out="$2" tempd="$3"
     local mtmp=$(mktemp -d "${tempd}/img_from_tar.XXXXXX")
@@ -93,8 +120,7 @@ squashfs_to_image() {
         return 1;
     }
         
-    out=$(mkfs.ext4 -O ^metadata_csum -F "$output" -L "cloudimg-rootfs" 2>&1) ||
-        { error "failed mkfs.ext4 -F '$output'"; return 1; }
+    mkfs_ext4 "$output" "$CLOUDIMG_LABEL" || return
     debug 1 "turning squahsfs image in $squashimg to ext4 image in $output"
     sudo bash -ec 'src="$1"; img="$2"; trgmp="$3";
         mounts=""
@@ -116,8 +142,7 @@ root_tar_to_image() {
     truncate "--size=$size" "$output" ||
         return "failed to create file of $size in $output"
     mkdir "$mp"
-    out=$(mkfs.ext4 -O ^metadata_csum -F "$output" -L "cloudimg-rootfs" 2>&1) ||
-        { error "failed mkfs.ext4 -F '$output'"; return 1; }
+    mkfs_ext4 "$output" "$CLOUDIMG_LABEL" || return
     debug 1 "turning root tarball in $tball to image in $output"
     sudo bash -ec 'tball="$1"; img="$2"; mp="$3";
         mount -o loop "$img" "$mp"
@@ -331,11 +356,7 @@ copy_filesystem_image() {
     truncate "--size=$size" "$target_img" ||
         { error "truncate $target_img $size failed"; return 1; }
     case "$fstype" in
-        ext*)
-            out=$("mkfs.$fstype" -F "$target_img" ${label:+-L "$label"} \
-                    ${uuid:+-U "${uuid}"} 2>&1) ||
-                { error "failed mkfs to $target_img: $out"; return 1; }
-            ;;
+        ext*) mkfs_ext4 "--type=$fstype" "$target_img" "$label" "$uuid";;
         *) error "unknown filesystem type '$fstype'";;
     esac
 
